# Game
FPS: int = 30

# Screen
CELL_MIN_PX_SIZE: int = 20
CELL_MAX_PX_SIZE: int = 80

# Animation
START_ANIMATION_FPS: int = 40
MIN_ANIMATION_FPS = 5
MAX_ANIMATION_FPS = 60
ANIMATION_SPEED_CHANGE = 3

# Colors
BLACK: tuple[int, int, int] = (0, 0, 0)
LIGHT_BLUE: tuple[int, int, int] = (138, 219, 239)
GRAY: tuple[int, int, int] = (220, 220, 220)

# Events
SCREEN_MOVE_CHANGE = 50
SCREEN_ZOOM_CHANGE = 5

# Algae
ALGA_SURFACING_STEPS: int = 15
ALGA_ENERGY_VALUE: int = 15
HOW_OFTEN_CYCLES_MAKING_ALGAE: int = 5

# Worm
WORM_FALLING_STEPS: int = 15
WORM_BOUNCE_STEPS: int = 20
WORM_ENERGY_VALUE: int = 30
NUM_OF_NEW_WORMS_AT_CYCLE: int = 3
HOW_OFTEN_CYCLES_MAKING_WORMS: int = 5
CHANCE_TO_PRODUCE_WORMS: int = 80  # in %

# Algae maker
MIN_ALGAE_TO_CREATE: int = 1
MAX_ALGAE_TO_CREATE: int = 3
CHANCE_TO_PRODUCE_ALGAE: int = 30  # in %

# Fish
FISH_MIN_SPEED: int = 5
FISH_MAX_SPEED: int = 10
FISH_MIN_SIZE: int = 5
FISH_MAX_SIZE: int = 10
FISH_NEED_MULTI_VITALITY_TO_BREED: int = 3
MIN_FISH_TO_BIRTH: int = 1
MAX_FISH_TO_BIRTH: int = 2
FISH_VITALITY_SPOIL_RATE: int = 1

# Evolution
EVOLUTION_DEVIATION_DIV: int = 10
