# Pond
POND_WIDTH: int = 5
POND_HEIGHT: int = 10

# Algae
ALGA_SURFACING_STEPS: int = 15
ALGA_ENERGY_VALUE: int = 15

# Fish
FISH_VITALITY_SPOIL_RATE: int = 1

# Worm
WORM_FALLING_STEPS: int = 15
WORM_BOUNCE_STEPS: int = 20
WORM_ENERGY_VALUE: int = 15

# Algae maker
MIN_ALGAE_TO_CREATE: int = 1
MAX_ALGAE_TO_CREATE: int = 3

# Fish
FISH_MIN_SPEED: int = 5
FISH_MAX_SPEED: int = 10
FISH_MIN_SIZE: int = 5
FISH_MAX_SIZE: int = 10
FISH_NEED_MULTI_VITALITY_TO_BREED: int = 2
MIN_FISH_TO_BIRTH: int = 1
MAX_FISH_TO_BIRTH: int = 2

# Evolution
EVOLUTION_DEVIATION_DIV = 10
