# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_pond_evolution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-custom_exit_code
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Unit tests
      run: |
        pytest --suppress-no-test-exit-code tests/unit
    - name: Integration tests
      run: |
        pytest --suppress-no-test-exit-code tests/integration
    - name: Type annotations check
      run: |
         mypy --config-file=mypy.ini
